// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TransactionManager is an autogenerated mock type for the TransactionManager type
type TransactionManager struct {
	mock.Mock
}

type TransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionManager) EXPECT() *TransactionManager_Expecter {
	return &TransactionManager_Expecter{mock: &_m.Mock}
}

// BeginTransaction provides a mock function with given fields:
func (_m *TransactionManager) BeginTransaction() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionManager_BeginTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTransaction'
type TransactionManager_BeginTransaction_Call struct {
	*mock.Call
}

// BeginTransaction is a helper method to define mock.On call
func (_e *TransactionManager_Expecter) BeginTransaction() *TransactionManager_BeginTransaction_Call {
	return &TransactionManager_BeginTransaction_Call{Call: _e.mock.On("BeginTransaction")}
}

func (_c *TransactionManager_BeginTransaction_Call) Run(run func()) *TransactionManager_BeginTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TransactionManager_BeginTransaction_Call) Return(_a0 string, _a1 error) *TransactionManager_BeginTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionManager_BeginTransaction_Call) RunAndReturn(run func() (string, error)) *TransactionManager_BeginTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// CommitTransaction provides a mock function with given fields: _a0
func (_m *TransactionManager) CommitTransaction(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CommitTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionManager_CommitTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitTransaction'
type TransactionManager_CommitTransaction_Call struct {
	*mock.Call
}

// CommitTransaction is a helper method to define mock.On call
//   - _a0 string
func (_e *TransactionManager_Expecter) CommitTransaction(_a0 interface{}) *TransactionManager_CommitTransaction_Call {
	return &TransactionManager_CommitTransaction_Call{Call: _e.mock.On("CommitTransaction", _a0)}
}

func (_c *TransactionManager_CommitTransaction_Call) Run(run func(_a0 string)) *TransactionManager_CommitTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TransactionManager_CommitTransaction_Call) Return(_a0 error) *TransactionManager_CommitTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionManager_CommitTransaction_Call) RunAndReturn(run func(string) error) *TransactionManager_CommitTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// IsActive provides a mock function with given fields: _a0
func (_m *TransactionManager) IsActive(_a0 string) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for IsActive")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// TransactionManager_IsActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsActive'
type TransactionManager_IsActive_Call struct {
	*mock.Call
}

// IsActive is a helper method to define mock.On call
//   - _a0 string
func (_e *TransactionManager_Expecter) IsActive(_a0 interface{}) *TransactionManager_IsActive_Call {
	return &TransactionManager_IsActive_Call{Call: _e.mock.On("IsActive", _a0)}
}

func (_c *TransactionManager_IsActive_Call) Run(run func(_a0 string)) *TransactionManager_IsActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TransactionManager_IsActive_Call) Return(_a0 bool) *TransactionManager_IsActive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionManager_IsActive_Call) RunAndReturn(run func(string) bool) *TransactionManager_IsActive_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackTransaction provides a mock function with given fields: _a0
func (_m *TransactionManager) RollbackTransaction(_a0 string) {
	_m.Called(_a0)
}

// TransactionManager_RollbackTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackTransaction'
type TransactionManager_RollbackTransaction_Call struct {
	*mock.Call
}

// RollbackTransaction is a helper method to define mock.On call
//   - _a0 string
func (_e *TransactionManager_Expecter) RollbackTransaction(_a0 interface{}) *TransactionManager_RollbackTransaction_Call {
	return &TransactionManager_RollbackTransaction_Call{Call: _e.mock.On("RollbackTransaction", _a0)}
}

func (_c *TransactionManager_RollbackTransaction_Call) Run(run func(_a0 string)) *TransactionManager_RollbackTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TransactionManager_RollbackTransaction_Call) Return() *TransactionManager_RollbackTransaction_Call {
	_c.Call.Return()
	return _c
}

func (_c *TransactionManager_RollbackTransaction_Call) RunAndReturn(run func(string)) *TransactionManager_RollbackTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionManager creates a new instance of TransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionManager {
	mock := &TransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
