---

mode: "techUI"

stat_fetcher_url: "http://data_server:1337"

postgres:
  host: "postgres"
  port: 5432
  user: "rauzh"
  password: "1337"
  db_name: "cook_droogers"

kafka:
  kafka_endpoints: ["kafka:9092", "kafka2:9092", "kafka3:9092"]
  kafka_settings: null

root:
  username: "root"
  password: "1337"

log:
  level: "debug"