---

mode: "techUI"

postgres:
  host: "postgres-slave"
  port: 5432
  user: "postgres"
  password: "1337"
  db_name: "cook_droogers"

kafka:
  kafka_endpoints: ["kafka:9092", "kafka2:9092", "kafka3:9092"]
  kafka_settings: null

root:
  username: "root@root.root"
  password: "1337"

log:
  level: "debug"