version: '3.8'

services:
  cook_droogers:
    image: cook-droogers-cook_droogers
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/rest-api --host 0.0.0.0 --port 8080
    ports:
      - "13337:8080"
    volumes:
      - ./cook_droogers.log:/app/cook_droogers.log
      - ./backend/config/config.yaml:/app/config.yaml
    depends_on:
      - kafka
      - kafka2
      - kafka3
      - postgres
    networks:
      - cookdroognet

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - cookdroognet
    depends_on:
      - zookeeper

  kafka2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka2
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - cookdroognet
    depends_on:
      - zookeeper

  kafka3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka3
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - cookdroognet
    depends_on:
      - zookeeper

  postgres:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "rauzh"
      POSTGRES_PASSWORD: "1337"
      POSTGRES_DB: "cook_droogers"
    volumes:
      - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cookdroognet

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - cookdroognet

  pgadmin:
    image: dpage/pgadmin4:7
    env_file:
      - .env
    ports:
      - 5435:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      TZ: "Europe/Moscow"
    depends_on:
      - postgres
    networks:
      - cookdroognet

networks:
  cookdroognet:
    driver: bridge