version: '3.8'

services:
  # cook_droogers:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - kafka
  #     - postgres
  #   networks:
  #     - cookdroognet

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # networks:
    #   - cookdroognet
    depends_on:
      - zookeeper

  postgres:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "rauzh"
      POSTGRES_PASSWORD: "1337"
      POSTGRES_DB: "cook_droogers"
    volumes:
      - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    # networks:
    #   - cookdroognet

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
#     networks:
#       - cookdroognet

# networks:
#   cookdroognet:
#     driver: bridge