// Code generated by go-swagger; DO NOT EDIT.

package requests

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SignContractHandlerFunc turns a function with the right signature into a sign contract handler
type SignContractHandlerFunc func(SignContractParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SignContractHandlerFunc) Handle(params SignContractParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SignContractHandler interface for that can handle valid sign contract params
type SignContractHandler interface {
	Handle(SignContractParams, interface{}) middleware.Responder
}

// NewSignContract creates a new http.Handler for the sign contract operation
func NewSignContract(ctx *middleware.Context, handler SignContractHandler) *SignContract {
	return &SignContract{Context: ctx, Handler: handler}
}

/*
	SignContract swagger:route POST /requests/contracts requests signContract

Create sign request
*/
type SignContract struct {
	Context *middleware.Context
	Handler SignContractHandler
}

func (o *SignContract) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSignContractParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
