// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AccessTokenDTO access token d t o
//
// swagger:model AccessTokenDTO
type AccessTokenDTO struct {

	// JWT access key
	AccessKey string `json:"access_key,omitempty"`
}

// Validate validates this access token d t o
func (m *AccessTokenDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this access token d t o based on context it is used
func (m *AccessTokenDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AccessTokenDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccessTokenDTO) UnmarshalBinary(b []byte) error {
	var res AccessTokenDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
