// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetArtistDTO get artist d t o
//
// swagger:model GetArtistDTO
type GetArtistDTO struct {

	// Использовать ли user_id вместо artist_id
	ByUserID bool `json:"by_user_id,omitempty"`
}

// Validate validates this get artist d t o
func (m *GetArtistDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get artist d t o based on context it is used
func (m *GetArtistDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetArtistDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetArtistDTO) UnmarshalBinary(b []byte) error {
	var res GetArtistDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
