// Code generated by go-swagger; DO NOT EDIT.

package artist

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"cookdroogers/internal/server/models"
)

// GetArtistByIDOKCode is the HTTP code returned for type GetArtistByIDOK
const GetArtistByIDOKCode int = 200

/*
GetArtistByIDOK Success

swagger:response getArtistByIdOK
*/
type GetArtistByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ArtistDTO `json:"body,omitempty"`
}

// NewGetArtistByIDOK creates GetArtistByIDOK with default headers values
func NewGetArtistByIDOK() *GetArtistByIDOK {

	return &GetArtistByIDOK{}
}

// WithPayload adds the payload to the get artist by Id o k response
func (o *GetArtistByIDOK) WithPayload(payload *models.ArtistDTO) *GetArtistByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get artist by Id o k response
func (o *GetArtistByIDOK) SetPayload(payload *models.ArtistDTO) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArtistByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetArtistByIDUnauthorizedCode is the HTTP code returned for type GetArtistByIDUnauthorized
const GetArtistByIDUnauthorizedCode int = 401

/*
GetArtistByIDUnauthorized Auth error

swagger:response getArtistByIdUnauthorized
*/
type GetArtistByIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.LeErrorMessage `json:"body,omitempty"`
}

// NewGetArtistByIDUnauthorized creates GetArtistByIDUnauthorized with default headers values
func NewGetArtistByIDUnauthorized() *GetArtistByIDUnauthorized {

	return &GetArtistByIDUnauthorized{}
}

// WithPayload adds the payload to the get artist by Id unauthorized response
func (o *GetArtistByIDUnauthorized) WithPayload(payload *models.LeErrorMessage) *GetArtistByIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get artist by Id unauthorized response
func (o *GetArtistByIDUnauthorized) SetPayload(payload *models.LeErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArtistByIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetArtistByIDForbiddenCode is the HTTP code returned for type GetArtistByIDForbidden
const GetArtistByIDForbiddenCode int = 403

/*
GetArtistByIDForbidden Invalid user type

swagger:response getArtistByIdForbidden
*/
type GetArtistByIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.LeErrorMessage `json:"body,omitempty"`
}

// NewGetArtistByIDForbidden creates GetArtistByIDForbidden with default headers values
func NewGetArtistByIDForbidden() *GetArtistByIDForbidden {

	return &GetArtistByIDForbidden{}
}

// WithPayload adds the payload to the get artist by Id forbidden response
func (o *GetArtistByIDForbidden) WithPayload(payload *models.LeErrorMessage) *GetArtistByIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get artist by Id forbidden response
func (o *GetArtistByIDForbidden) SetPayload(payload *models.LeErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArtistByIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetArtistByIDNotFoundCode is the HTTP code returned for type GetArtistByIDNotFound
const GetArtistByIDNotFoundCode int = 404

/*
GetArtistByIDNotFound No such artist

swagger:response getArtistByIdNotFound
*/
type GetArtistByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.LeErrorMessage `json:"body,omitempty"`
}

// NewGetArtistByIDNotFound creates GetArtistByIDNotFound with default headers values
func NewGetArtistByIDNotFound() *GetArtistByIDNotFound {

	return &GetArtistByIDNotFound{}
}

// WithPayload adds the payload to the get artist by Id not found response
func (o *GetArtistByIDNotFound) WithPayload(payload *models.LeErrorMessage) *GetArtistByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get artist by Id not found response
func (o *GetArtistByIDNotFound) SetPayload(payload *models.LeErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArtistByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetArtistByIDUnprocessableEntityCode is the HTTP code returned for type GetArtistByIDUnprocessableEntity
const GetArtistByIDUnprocessableEntityCode int = 422

/*
GetArtistByIDUnprocessableEntity Invalid params

swagger:response getArtistByIdUnprocessableEntity
*/
type GetArtistByIDUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.LeErrorMessage `json:"body,omitempty"`
}

// NewGetArtistByIDUnprocessableEntity creates GetArtistByIDUnprocessableEntity with default headers values
func NewGetArtistByIDUnprocessableEntity() *GetArtistByIDUnprocessableEntity {

	return &GetArtistByIDUnprocessableEntity{}
}

// WithPayload adds the payload to the get artist by Id unprocessable entity response
func (o *GetArtistByIDUnprocessableEntity) WithPayload(payload *models.LeErrorMessage) *GetArtistByIDUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get artist by Id unprocessable entity response
func (o *GetArtistByIDUnprocessableEntity) SetPayload(payload *models.LeErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArtistByIDUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetArtistByIDInternalServerErrorCode is the HTTP code returned for type GetArtistByIDInternalServerError
const GetArtistByIDInternalServerErrorCode int = 500

/*
GetArtistByIDInternalServerError Internal error

swagger:response getArtistByIdInternalServerError
*/
type GetArtistByIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.LeErrorMessage `json:"body,omitempty"`
}

// NewGetArtistByIDInternalServerError creates GetArtistByIDInternalServerError with default headers values
func NewGetArtistByIDInternalServerError() *GetArtistByIDInternalServerError {

	return &GetArtistByIDInternalServerError{}
}

// WithPayload adds the payload to the get artist by Id internal server error response
func (o *GetArtistByIDInternalServerError) WithPayload(payload *models.LeErrorMessage) *GetArtistByIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get artist by Id internal server error response
func (o *GetArtistByIDInternalServerError) SetPayload(payload *models.LeErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArtistByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
