// Code generated by go-swagger; DO NOT EDIT.

package non_member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"cookdroogers/internal/handlers/models"
)

// GetRequestOKCode is the HTTP code returned for type GetRequestOK
const GetRequestOKCode int = 200

/*
GetRequestOK Success

swagger:response getRequestOK
*/
type GetRequestOK struct {

	/*
	  In: Body
	*/
	Payload *models.PublishRequestDTO `json:"body,omitempty"`
}

// NewGetRequestOK creates GetRequestOK with default headers values
func NewGetRequestOK() *GetRequestOK {

	return &GetRequestOK{}
}

// WithPayload adds the payload to the get request o k response
func (o *GetRequestOK) WithPayload(payload *models.PublishRequestDTO) *GetRequestOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get request o k response
func (o *GetRequestOK) SetPayload(payload *models.PublishRequestDTO) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRequestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRequestInternalServerErrorCode is the HTTP code returned for type GetRequestInternalServerError
const GetRequestInternalServerErrorCode int = 500

/*
GetRequestInternalServerError Internal error

swagger:response getRequestInternalServerError
*/
type GetRequestInternalServerError struct {
}

// NewGetRequestInternalServerError creates GetRequestInternalServerError with default headers values
func NewGetRequestInternalServerError() *GetRequestInternalServerError {

	return &GetRequestInternalServerError{}
}

// WriteResponse to the client
func (o *GetRequestInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
