// Code generated by go-swagger; DO NOT EDIT.

package non_member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SignContractCreatedCode is the HTTP code returned for type SignContractCreated
const SignContractCreatedCode int = 201

/*
SignContractCreated Request successfully created

swagger:response signContractCreated
*/
type SignContractCreated struct {
}

// NewSignContractCreated creates SignContractCreated with default headers values
func NewSignContractCreated() *SignContractCreated {

	return &SignContractCreated{}
}

// WriteResponse to the client
func (o *SignContractCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// SignContractBadRequestCode is the HTTP code returned for type SignContractBadRequest
const SignContractBadRequestCode int = 400

/*
SignContractBadRequest Invalid request fields

swagger:response signContractBadRequest
*/
type SignContractBadRequest struct {
}

// NewSignContractBadRequest creates SignContractBadRequest with default headers values
func NewSignContractBadRequest() *SignContractBadRequest {

	return &SignContractBadRequest{}
}

// WriteResponse to the client
func (o *SignContractBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// SignContractForbiddenCode is the HTTP code returned for type SignContractForbidden
const SignContractForbiddenCode int = 403

/*
SignContractForbidden Invalid user type

swagger:response signContractForbidden
*/
type SignContractForbidden struct {
}

// NewSignContractForbidden creates SignContractForbidden with default headers values
func NewSignContractForbidden() *SignContractForbidden {

	return &SignContractForbidden{}
}

// WriteResponse to the client
func (o *SignContractForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// SignContractInternalServerErrorCode is the HTTP code returned for type SignContractInternalServerError
const SignContractInternalServerErrorCode int = 500

/*
SignContractInternalServerError Internal error

swagger:response signContractInternalServerError
*/
type SignContractInternalServerError struct {
}

// NewSignContractInternalServerError creates SignContractInternalServerError with default headers values
func NewSignContractInternalServerError() *SignContractInternalServerError {

	return &SignContractInternalServerError{}
}

// WriteResponse to the client
func (o *SignContractInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
