// Code generated by go-swagger; DO NOT EDIT.

package artists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetArtistByUsernameParams creates a new GetArtistByUsernameParams object
//
// There are no default values defined in the spec.
func NewGetArtistByUsernameParams() GetArtistByUsernameParams {

	return GetArtistByUsernameParams{}
}

// GetArtistByUsernameParams contains all the bound params for the get artist by username operation
// typically these are obtained from a http.Request
//
// swagger:parameters getArtistByUsername
type GetArtistByUsernameParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*username артиста (пользователя)
	  Required: true
	  In: path
	*/
	Username strfmt.Email
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetArtistByUsernameParams() beforehand.
func (o *GetArtistByUsernameParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rUsername, rhkUsername, _ := route.Params.GetOK("username")
	if err := o.bindUsername(rUsername, rhkUsername, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindUsername binds and validates parameter Username from path.
func (o *GetArtistByUsernameParams) bindUsername(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: email
	value, err := formats.Parse("email", raw)
	if err != nil {
		return errors.InvalidType("username", "path", "strfmt.Email", raw)
	}
	o.Username = *(value.(*strfmt.Email))

	if err := o.validateUsername(formats); err != nil {
		return err
	}

	return nil
}

// validateUsername carries on validations for parameter Username
func (o *GetArtistByUsernameParams) validateUsername(formats strfmt.Registry) error {

	if err := validate.FormatOf("username", "path", "email", o.Username.String(), formats); err != nil {
		return err
	}
	return nil
}
