// Code generated by go-swagger; DO NOT EDIT.

package artists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetArtistByIDHandlerFunc turns a function with the right signature into a get artist by ID handler
type GetArtistByIDHandlerFunc func(GetArtistByIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetArtistByIDHandlerFunc) Handle(params GetArtistByIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetArtistByIDHandler interface for that can handle valid get artist by ID params
type GetArtistByIDHandler interface {
	Handle(GetArtistByIDParams, interface{}) middleware.Responder
}

// NewGetArtistByID creates a new http.Handler for the get artist by ID operation
func NewGetArtistByID(ctx *middleware.Context, handler GetArtistByIDHandler) *GetArtistByID {
	return &GetArtistByID{Context: ctx, Handler: handler}
}

/*
	GetArtistByID swagger:route GET /artists/{id} artists getArtistById

Get artist data
*/
type GetArtistByID struct {
	Context *middleware.Context
	Handler GetArtistByIDHandler
}

func (o *GetArtistByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetArtistByIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
