// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetHeartbeatOKCode is the HTTP code returned for type GetHeartbeatOK
const GetHeartbeatOKCode int = 200

/*
GetHeartbeatOK Success

swagger:response getHeartbeatOK
*/
type GetHeartbeatOK struct {
}

// NewGetHeartbeatOK creates GetHeartbeatOK with default headers values
func NewGetHeartbeatOK() *GetHeartbeatOK {

	return &GetHeartbeatOK{}
}

// WriteResponse to the client
func (o *GetHeartbeatOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
