// Code generated by go-swagger; DO NOT EDIT.

package manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewAcceptRequestParams creates a new AcceptRequestParams object
//
// There are no default values defined in the spec.
func NewAcceptRequestParams() AcceptRequestParams {

	return AcceptRequestParams{}
}

// AcceptRequestParams contains all the bound params for the accept request operation
// typically these are obtained from a http.Request
//
// swagger:parameters acceptRequest
type AcceptRequestParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID заявки
	  Required: true
	  In: path
	*/
	ReqID uint64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAcceptRequestParams() beforehand.
func (o *AcceptRequestParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rReqID, rhkReqID, _ := route.Params.GetOK("req_id")
	if err := o.bindReqID(rReqID, rhkReqID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindReqID binds and validates parameter ReqID from path.
func (o *AcceptRequestParams) bindReqID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertUint64(raw)
	if err != nil {
		return errors.InvalidType("req_id", "path", "uint64", raw)
	}
	o.ReqID = value

	return nil
}
