// Code generated by go-swagger; DO NOT EDIT.

package manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FetchStatsHandlerFunc turns a function with the right signature into a fetch stats handler
type FetchStatsHandlerFunc func(FetchStatsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn FetchStatsHandlerFunc) Handle(params FetchStatsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// FetchStatsHandler interface for that can handle valid fetch stats params
type FetchStatsHandler interface {
	Handle(FetchStatsParams, interface{}) middleware.Responder
}

// NewFetchStats creates a new http.Handler for the fetch stats operation
func NewFetchStats(ctx *middleware.Context, handler FetchStatsHandler) *FetchStats {
	return &FetchStats{Context: ctx, Handler: handler}
}

/*
	FetchStats swagger:route POST /fetch-stats manager fetchStats

Fetch statistics for manager's artists
*/
type FetchStats struct {
	Context *middleware.Context
	Handler FetchStatsHandler
}

func (o *FetchStats) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFetchStatsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
