// Code generated by go-swagger; DO NOT EDIT.

package manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetManagerByIDParams creates a new GetManagerByIDParams object
//
// There are no default values defined in the spec.
func NewGetManagerByIDParams() GetManagerByIDParams {

	return GetManagerByIDParams{}
}

// GetManagerByIDParams contains all the bound params for the get manager by ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters getManagerByID
type GetManagerByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID менеджера
	  Required: true
	  In: path
	*/
	ManagerID uint64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetManagerByIDParams() beforehand.
func (o *GetManagerByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rManagerID, rhkManagerID, _ := route.Params.GetOK("manager_id")
	if err := o.bindManagerID(rManagerID, rhkManagerID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindManagerID binds and validates parameter ManagerID from path.
func (o *GetManagerByIDParams) bindManagerID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertUint64(raw)
	if err != nil {
		return errors.InvalidType("manager_id", "path", "uint64", raw)
	}
	o.ManagerID = value

	return nil
}
