// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetUserByEmailHandlerFunc turns a function with the right signature into a get user by email handler
type GetUserByEmailHandlerFunc func(GetUserByEmailParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserByEmailHandlerFunc) Handle(params GetUserByEmailParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetUserByEmailHandler interface for that can handle valid get user by email params
type GetUserByEmailHandler interface {
	Handle(GetUserByEmailParams, interface{}) middleware.Responder
}

// NewGetUserByEmail creates a new http.Handler for the get user by email operation
func NewGetUserByEmail(ctx *middleware.Context, handler GetUserByEmailHandler) *GetUserByEmail {
	return &GetUserByEmail{Context: ctx, Handler: handler}
}

/*
	GetUserByEmail swagger:route GET /users/email/{email} users getUserByEmail

Get user dat by email
*/
type GetUserByEmail struct {
	Context *middleware.Context
	Handler GetUserByEmailHandler
}

func (o *GetUserByEmail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetUserByEmailParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
