// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	models "cookdroogers/models"

	mock "github.com/stretchr/testify/mock"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

type UserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepo) EXPECT() *UserRepo_Expecter {
	return &UserRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0
func (_m *UserRepo) Create(_a0 *models.User) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 *models.User
func (_e *UserRepo_Expecter) Create(_a0 interface{}) *UserRepo_Create_Call {
	return &UserRepo_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *UserRepo_Create_Call) Run(run func(_a0 *models.User)) *UserRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.User))
	})
	return _c
}

func (_c *UserRepo_Create_Call) Return(_a0 error) *UserRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepo_Create_Call) RunAndReturn(run func(*models.User) error) *UserRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: _a0
func (_m *UserRepo) Get(_a0 uint64) (*models.User, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*models.User, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uint64) *models.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UserRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 uint64
func (_e *UserRepo_Expecter) Get(_a0 interface{}) *UserRepo_Get_Call {
	return &UserRepo_Get_Call{Call: _e.mock.On("Get", _a0)}
}

func (_c *UserRepo_Get_Call) Run(run func(_a0 uint64)) *UserRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *UserRepo_Get_Call) Return(_a0 *models.User, _a1 error) *UserRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepo_Get_Call) RunAndReturn(run func(uint64) (*models.User, error)) *UserRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: _a0
func (_m *UserRepo) GetByEmail(_a0 string) (*models.User, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.User, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserRepo_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - _a0 string
func (_e *UserRepo_Expecter) GetByEmail(_a0 interface{}) *UserRepo_GetByEmail_Call {
	return &UserRepo_GetByEmail_Call{Call: _e.mock.On("GetByEmail", _a0)}
}

func (_c *UserRepo_GetByEmail_Call) Run(run func(_a0 string)) *UserRepo_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *UserRepo_GetByEmail_Call) Return(_a0 *models.User, _a1 error) *UserRepo_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepo_GetByEmail_Call) RunAndReturn(run func(string) (*models.User, error)) *UserRepo_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0
func (_m *UserRepo) Update(_a0 *models.User) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 *models.User
func (_e *UserRepo_Expecter) Update(_a0 interface{}) *UserRepo_Update_Call {
	return &UserRepo_Update_Call{Call: _e.mock.On("Update", _a0)}
}

func (_c *UserRepo_Update_Call) Run(run func(_a0 *models.User)) *UserRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.User))
	})
	return _c
}

func (_c *UserRepo_Update_Call) Return(_a0 error) *UserRepo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepo_Update_Call) RunAndReturn(run func(*models.User) error) *UserRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateType provides a mock function with given fields: userID, typ
func (_m *UserRepo) UpdateType(userID uint64, typ models.UserType) error {
	ret := _m.Called(userID, typ)

	if len(ret) == 0 {
		panic("no return value specified for UpdateType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, models.UserType) error); ok {
		r0 = rf(userID, typ)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepo_UpdateType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateType'
type UserRepo_UpdateType_Call struct {
	*mock.Call
}

// UpdateType is a helper method to define mock.On call
//   - userID uint64
//   - typ models.UserType
func (_e *UserRepo_Expecter) UpdateType(userID interface{}, typ interface{}) *UserRepo_UpdateType_Call {
	return &UserRepo_UpdateType_Call{Call: _e.mock.On("UpdateType", userID, typ)}
}

func (_c *UserRepo_UpdateType_Call) Run(run func(userID uint64, typ models.UserType)) *UserRepo_UpdateType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64), args[1].(models.UserType))
	})
	return _c
}

func (_c *UserRepo_UpdateType_Call) Return(_a0 error) *UserRepo_UpdateType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepo_UpdateType_Call) RunAndReturn(run func(uint64, models.UserType) error) *UserRepo_UpdateType_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
