// Code generated by go-swagger; DO NOT EDIT.

package manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetManagerByIDHandlerFunc turns a function with the right signature into a get manager by ID handler
type GetManagerByIDHandlerFunc func(GetManagerByIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetManagerByIDHandlerFunc) Handle(params GetManagerByIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetManagerByIDHandler interface for that can handle valid get manager by ID params
type GetManagerByIDHandler interface {
	Handle(GetManagerByIDParams, interface{}) middleware.Responder
}

// NewGetManagerByID creates a new http.Handler for the get manager by ID operation
func NewGetManagerByID(ctx *middleware.Context, handler GetManagerByIDHandler) *GetManagerByID {
	return &GetManagerByID{Context: ctx, Handler: handler}
}

/*
	GetManagerByID swagger:route GET /managers/{manager_id} manager getManagerById

Get manager data
*/
type GetManagerByID struct {
	Context *middleware.Context
	Handler GetManagerByIDHandler
}

func (o *GetManagerByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetManagerByIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
