// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PublishRequestDTO publish request d t o
//
// swagger:model PublishRequestDTO
type PublishRequestDTO struct {

	// base
	Base *RequestDTO `json:"base,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// expected date
	// Format: date
	ExpectedDate strfmt.Date `json:"expected_date,omitempty"`

	// grade
	Grade int64 `json:"grade,omitempty"`

	// release id
	ReleaseID uint64 `json:"release_id,omitempty"`
}

// Validate validates this publish request d t o
func (m *PublishRequestDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBase(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpectedDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PublishRequestDTO) validateBase(formats strfmt.Registry) error {
	if swag.IsZero(m.Base) { // not required
		return nil
	}

	if m.Base != nil {
		if err := m.Base.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("base")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("base")
			}
			return err
		}
	}

	return nil
}

func (m *PublishRequestDTO) validateExpectedDate(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpectedDate) { // not required
		return nil
	}

	if err := validate.FormatOf("expected_date", "body", "date", m.ExpectedDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this publish request d t o based on the context it is used
func (m *PublishRequestDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBase(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PublishRequestDTO) contextValidateBase(ctx context.Context, formats strfmt.Registry) error {

	if m.Base != nil {

		if swag.IsZero(m.Base) { // not required
			return nil
		}

		if err := m.Base.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("base")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("base")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PublishRequestDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublishRequestDTO) UnmarshalBinary(b []byte) error {
	var res PublishRequestDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
