// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PublishRequestInput publish request input
//
// swagger:model PublishRequestInput
type PublishRequestInput struct {

	// expected date
	// Format: date
	ExpectedDate strfmt.Date `json:"expected_date,omitempty"`

	// release id
	ReleaseID uint64 `json:"release_id,omitempty"`
}

// Validate validates this publish request input
func (m *PublishRequestInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpectedDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PublishRequestInput) validateExpectedDate(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpectedDate) { // not required
		return nil
	}

	if err := validate.FormatOf("expected_date", "body", "date", m.ExpectedDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this publish request input based on context it is used
func (m *PublishRequestInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PublishRequestInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublishRequestInput) UnmarshalBinary(b []byte) error {
	var res PublishRequestInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
