// Code generated by go-swagger; DO NOT EDIT.

package artist

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PublishReqCreatedCode is the HTTP code returned for type PublishReqCreated
const PublishReqCreatedCode int = 201

/*
PublishReqCreated Request successfully created

swagger:response publishReqCreated
*/
type PublishReqCreated struct {
}

// NewPublishReqCreated creates PublishReqCreated with default headers values
func NewPublishReqCreated() *PublishReqCreated {

	return &PublishReqCreated{}
}

// WriteResponse to the client
func (o *PublishReqCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PublishReqBadRequestCode is the HTTP code returned for type PublishReqBadRequest
const PublishReqBadRequestCode int = 400

/*
PublishReqBadRequest Invalid request fields

swagger:response publishReqBadRequest
*/
type PublishReqBadRequest struct {
}

// NewPublishReqBadRequest creates PublishReqBadRequest with default headers values
func NewPublishReqBadRequest() *PublishReqBadRequest {

	return &PublishReqBadRequest{}
}

// WriteResponse to the client
func (o *PublishReqBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PublishReqForbiddenCode is the HTTP code returned for type PublishReqForbidden
const PublishReqForbiddenCode int = 403

/*
PublishReqForbidden Invalid user type

swagger:response publishReqForbidden
*/
type PublishReqForbidden struct {
}

// NewPublishReqForbidden creates PublishReqForbidden with default headers values
func NewPublishReqForbidden() *PublishReqForbidden {

	return &PublishReqForbidden{}
}

// WriteResponse to the client
func (o *PublishReqForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// PublishReqInternalServerErrorCode is the HTTP code returned for type PublishReqInternalServerError
const PublishReqInternalServerErrorCode int = 500

/*
PublishReqInternalServerError Internal error

swagger:response publishReqInternalServerError
*/
type PublishReqInternalServerError struct {
}

// NewPublishReqInternalServerError creates PublishReqInternalServerError with default headers values
func NewPublishReqInternalServerError() *PublishReqInternalServerError {

	return &PublishReqInternalServerError{}
}

// WriteResponse to the client
func (o *PublishReqInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
