// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Swagger-Cook-Droogers
//
//	Schemes:
//	  http
//	Host: 0.0.0.0:8081
//	BasePath: /api/v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
